# Generated by Django 3.2.6 on 2021-09-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilestat',
            name='answer_number',
        ),
    ]
