# Generated by Django 3.2.6 on 2021-09-14 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofilestat_answer_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofilestat',
            options={'verbose_name': 'User Profile Answer', 'verbose_name_plural': 'User Profile Answers'},
        ),
    ]
