# Generated by Django 3.2.6 on 2021-09-05 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_useranswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'User answer', 'verbose_name_plural': 'User answers'},
        ),
    ]
