# Generated by Django 3.2.6 on 2021-09-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_useranswer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='user_answer',
            field=models.CharField(max_length=60),
        ),
    ]
